### ISSUE TITLE
bo-class not working when interpolation is used on same element

### ISSUE THREAD

**Issue by snicker** [Pasvaz/bindonce#35]
In the code below:
`<a bo-class='{label-positive: model.positive}' class="label float-label label-level-{{model.level}}"></a>`

The "label-positive" class will never get attached. If the `{{model.level}}` interpolation is removed, it is added fine.

The following works perfectly.
`<a ng-class='{label-positive: model.positive}' class="label float-label label-level-{{model.level}}"></a>`

could this be an issue with directive priority?

**Comment by snicker** [comment]
see this plunkr for example:
http://plnkr.co/edit/7EMe8RmIklDUTYkkJJv1?p=preview

This is in angular 1.2

**Comment by Pasvaz** [comment]
@snicker sorry for letting you wait, I had to work on something else and only now I can spend some time on bindonce. I checked your plnkr and it seems that the interpolation override `bo-class`. 
Yes it's a matter of priority, but you can use `ng-class` instead of interpolation at the same cost in terms of watchers and it works:

``` javascript
<div ng-class='"label-level-"+model.level' bo-class='{"label-positive": model.positive}' class="label ">with interpolation, with bo-class directive</div>
```

This line still requires one watcher like the interpolation does but it doesn't override `bo-class`.
This cose is just a demo of course, once you use `ng-class` or interpolation you can produce all the class attribute for that `div` with one watcher, you don't need to add `bo-class`.
