### ISSUE TITLE
Brackets?

### ISSUE THREAD

**Issue by fxck** [Pasvaz/bindonce#47]
Is there any particular reason why there's no bracket version of bo-text, similar to angular's ng-bind / {{}} combo? Is it not possible, or none thought about it before?

**Comment by Pasvaz** [comment]
the brackets are used by Angular, in order to use them you should change the interpolation symbols but this would break your existing code, another way would be to use a function inside the brackets but this would be useless since Angular will still use a watcher for it.

**Comment by fxck** [comment]
I was talking about brackets in general, not neccesarily the same as used by angular. bindonce could have their own, say `[[]]`..

**Comment by Pasvaz** [comment]
If you don't use the angular interpolation you should create your own interpolation provider and this would be expensive in term of performance while you can obtain exactly the same result just using a span with bo-text or one of the other bo-\* directive. When you do `{{ someValue }}` under the cover is exactly like if you created a span with one binding inside: `<span ng-bind="someValue"></span>` and actually it's even better the ng-bind form because you'll not see the {{}} in the DOM while angular bootstraps.
