### ISSUE TITLE
Bindonce doesn't work with AngularJs promises

### ISSUE THREAD

**Issue by MichielDeMey** [Pasvaz/bindonce#57]
Bindonce doesn't seem to play well with AngularJs promises. (v1.2.11)

This doesn't work:

```
$scope.app = App.get({id: Id}, function (result) {
    // This callback is used purely for debugging
    console.log('Got app details', result);
});
```

But this does:

```
App.get({id: Id}, function (result) {
    // This callback is used purely for debugging
    console.log('Got app details', result);

    $scope.app = result;
});
```

AngularJs wil automatically fill the scope variable with the values of the promise when it's returned and set the $promise.resolved to true.

Note that at initialization, the promise is created but not resolved. (`$promise.resolved = false`)

That doesn't play well with bindonce, because bindonce will wait until a scope variable is set. But it's set with `$promise.resolved = false`.

What I propose is checking a scope variable for the $promise object, and when it's present wait until it is resolved (or not).

I regret that I currently don't have the time to create a pull request for this, but using my solution I can work around this issue for now.

**Comment by Pasvaz** [comment]
Thank you for reporting it @MichielDeMey I'll fix it asap.

**Comment by rileylark** [comment]
I think angular plans on removing the promise resolution in 1.3. FYI

**Comment by Pasvaz** [comment]
true, but Angular is also planning to add a bindonce-ish feature in 1.3 :)

**Comment by Pasvaz** [comment]
@MichielDeMey can you post a complete use case when it's necessary to bind a promise with bindonce?

The commit b3ef1b46edfe83f10ed455d5520027f731563f32 handles promises but I'm not sure it's a good thing, you should better bindonce the data rather than the promise itself, maybe I'm missing something I'm curious to see how you used bindonce.

Also, I guess you were speaking about $resources rather than promises, $http return a promise while $resource return a wrapper object that contains the promise inside $promise and the status value inside $resolved, so in this case the above mentioned commit doesn't help, I should add the $resource use case.

**Comment by MichielDeMey** [comment]
Yes, I was talking about $resource. Sorry about that.

Furthermore, there really isn't a use-case to bind promises over the data itself except for the ease of use.

But like I stated in the original post, everything can be solved by setting the scope variable inside the callback function and then bindonce to that variable to wait until it's available.

So there really isn't an issue here.

**Comment by Pasvaz** [comment]
Ok, the commit cf26760fb9c968a60ea54ae60f33977e80183a94 handles also $resource as bindonce value, however I wouldn't suggest to use bindonce in this way nor to rely on this commit that could be removed in the future. 
Binding directly a promise can be an issue because runBinders is ran before than the actual data are bound to the scope, so it must run again for each bo-\* directive. The best practice here is to use the second approach you showed, binding the data from the $resource to the scope variable you use as bindonce.
